/**
 * This file's purpose is to inject all the assets
 * generated by Fuse-Box into the service worker.
 *
 * The config is available at:
 * https://developers.google.com/web/tools/workbox/modules/workbox-cli
 */
module.exports = {
  globDirectory: './dist/',
  globPatterns: ['**/*.{html,js,css,png}'],
  swDest: './dist/sw.js',
  swSrc: './public/sw.js',
  injectionPointRegexp: /(cached\s=\s)\[\s*\](\;)/,
};
